pipeline {
   agent any
	environment {
		USER_NAME="prashanth"
		USER_ID = 4
		}
      stages {
        stage ("GIT CHECKOUT"){
	  steps {
	      git branch: 'main', url: 'https://github.com/prashanth19975/Deploy-to-docker-container.git'
	     }
	     }
	      stage("env") {
		      steps {
			      echo "BUILD_NUMBER = ${env.BUILD_NUMBER}"  
			      sh "echo BUILD_NUMBER = $BUILD_NUMBER"
			      }
			      }
	      stage("env1") {
		      steps {
			      echo "CURRENT_USER=${env.USER_NAME}"
			      sh "echo USER_NAME= $USER_NAME" (type: ${env.USER_ID.class})
		      }
	      }
	 }
 }	 
